# app.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 3600
      containers:
      - image: gcr.io/PROJECT_ID/crypto-alpha-analysis
        env:
        - name: ALCHEMY_API_KEY
          value: "your-alchemy-key"
        - name: SECRET_KEY
          value: "your-secret-key"
        - name: APP_PASSWORD
          value: "your-app-password"
        - name: MONGO_URI
          value: "mongodb://username:password@host:port/database"
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
        ports:
        - containerPort: 8080