services:
  - type: web
    name: crypto-analysis-api
    env: python
    region: singapore
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: MONGO_URI
        sync: false
      - key: ALCHEMY_API_KEY
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false
    healthCheckPath: /health
    
  - type: worker
    name: crypto-monitor-worker
    env: python
    region: singapore
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python auto_monitor.py
    envVars:
      - key: MONGO_URI
        sync: false
      - key: ALCHEMY_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false